apiVersion: batch/v1
kind: Job
metadata:
  name: createdb-notifications
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: createdb-notifications
        image: postgres:10-alpine
        command:
        - bash
        - -x
        - -c
        - >
          { PGPASSWORD=payments psql -U notifications -h postgres -d notifications -ql; }
          || {
          psql -h postgres -d postgres -c "CREATE ROLE notifications WITH PASSWORD 'notifications' LOGIN REPLICATION";
          psql -h postgres -d postgres -c "CREATE DATABASE notifications OWNER notifications";
          psql -h postgres -d notifications -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"' || true; }
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: postgres-password
        - name: PGUSER
          value: postgres

