[server]
host = "0.0.0.0"
port = 8000

[client]
dns_threads = 4

[database]
url = "postgresql://payments-notifications:payments-notifications@payments-notifications-pg/payments-notifications"

[cpu_pool]
size = 1

[rabbit]
url = "amqp://guest:guest@localhost:5672//?heartbeat=3&frame_max=131072"
thread_pool_size = 2
connection_timeout_secs = 10
connection_pool_size = 10
restart_subscription_secs = 30

[ios_credentials]
ios_url = "",
ios_token = "",
ios_user_id = "",
